spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    #local
    #url: jdbc:postgresql://localhost:5432/dbsmartclinic
    #username: postgres
    #password: root

    #dynamic
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

server:
  port: 8080