spring:
  jpa:
    hibernate:
      ddl-auto: update
      dynamic-insert: true
      dynamic-update: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/smartclinicdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 8081