spring:
  jpa:
    hibernate:
      ddl-auto: update
      dynamic-insert: true
      dynamic-update: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #dynamic
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

    #local
    #url: jdbc:postgresql://localhost:5432/smartclinicdb
    #username: postgres
    #password: root

    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:5000}