spring:
  jpa:
    hibernate:
      ddl-auto: update
      dynamic-insert: true
      dynamic-update: true
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
server:
  port: ${PORT:5000}
