spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #local
    url: jdbc:postgresql://localhost:5432/dbsmartclinic
    username: postgres
    password: root

    #dynamic
    #url: ${JDBC_DATABASE_URL:}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

    driver-class-name: org.postgresql.Driver